CREATE TABLE BRANCH
(
    BRANCHNO NUMBER(20) CONSTRAINT PK_BRANCHNO PRIMARY KEY,
    BRANCHNAME VARCHAR2(30)
);
DESCRIBE BRANCH;

CREATE TABLE HOMETOWN
(
    HOMETOWNNO NUMBER(10) CONSTRAINT PK_HOMETOWNNO PRIMARY KEY,
    HOMETOWNNAME VARCHAR2(20)
);
DESCRIBE HOMETOWN;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(20) CONSTRAINT PK_EMPNO PRIMARY KEY,
    SALARY NUMBER(10),
    GENDER VARCHAR2(15),
    JOINDATE DATE,
    HOMETOWNNO NUMBER(20) CONSTRAINT FK_HOMETOWNNO REFERENCES HOMETOWN
);
DESCRIBE EMPLOYEE;

CREATE TABLE CUSTOMER
(
     CUSNO NUMBER(25) CONSTRAINT PK_CUSNO PRIMARY KEY,
     ADDRESS VARCHAR2(30),
     BKASH VARCHAR2(30),
     NAGAD VARCHAR2(30),
     CCARD VARCHAR2(30),
     EMPNO CONSTRAINT FK_CEMPNO REFERENCES EMPLOYEE
);
DESCRIBE CUSTOMER;

CREATE TABLE PERSON
(
    NAME VARCHAR2(35),
    PHONE VARCHAR2(25),
    DOB DATE,
    EMPNO NUMBER(25) CONSTRAINT FK_EMPNO REFERENCES EMPLOYEE,
    CUSNO NUMBER(25) CONSTRAINT FK_CUSNO REFERENCES CUSTOMER
);
DESCRIBE PERSON;

CREATE TABLE PIZZA
(
     PIZZANO NUMBER(35) CONSTRAINT PK_PIZZANO PRIMARY KEY,     
     PIZZANAME VARCHAR2(25),
     STOCK NUMBER(30),
     PRICE NUMBER(30),
     PROFIT NUMBER(30) 
);
DESCRIBE PIZZA;

CREATE TABLE RECEIPT
(
     ORDERNO NUMBER(25) CONSTRAINT PK_ODERNO PRIMARY KEY,     
     STATUS VARCHAR2(15) 
);
DESCRIBE RECEIPT;


CREATE TABLE GRADE 
(
    GRADENAME VARCHAR2(25), 
    LOWGRADE NUMBER(25),
    HIGHGRADE NUMBER(25)
);
DESCRIBE GRADE;
-----------------------
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;
SELECT * FROM HOMETOWN;
SELECT * FROM GRADE;
SELECT * FROM PERSON;
SELECT * FROM PIZZA;
SELECT * FROM RECEIPT;
-----------------------
DESCRIBE BRANCH;
DESCRIBE CUSTOMER;
DESCRIBE EMPLOYEE;
DESCRIBE HOMETOWN;
DESCRIBE GRADE;
DESCRIBE PERSON;
DESCRIBE PIZZA;
DESCRIBE RECEIPT;
-----------------------
-- Sequence
CREATE SEQUENCE CUSTOMER_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE EMPLOYEE_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE BRANCH_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE HOMETOWN_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE GRADE_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE PERSON_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE PIZZA_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE RECEIPT_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;



------INSERT BRANCH

INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT MIRPUR');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT UTTARA');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT DHANMONDI');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT MOHAMMADPUR');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT BASUNDHARA');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT GULSHAN');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT FARMGATE');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PIZZA HUTT BANANI');
SELECT * FROM BRANCH;

--------INSERT HOMETOWN: 

INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'GAZIPUR');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'GOPALGANJ');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'MADARIPUR');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'NARSHINGDI');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'PATUAKHALI');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'BHOLA');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'BRAHMANBARIA');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'JAMALPUR');
INSERT INTO HOMETOWN VALUES(HOMETOWN_SEQUENCE.NEXTVAL,'NETROKONA');

SELECT * FROM HOMETOWN;

-------EMPLOYEE TABLE INSERTION 

ALTER TABLE EMPLOYEE ADD(BRANCHNO NUMBER(15) CONSTRAINT FK_EBRANCH REFERENCES BRANCH);

INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,5500,'MALE',TO_DATE('01-06-2019','DD-MM-YY'),10,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6500,'MALE',TO_DATE('01-03-2020','DD-MM-YY'),10,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,5500,'MALE',TO_DATE('05-08-2016','DD-MM-YY'),20,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6000,'MALE',TO_DATE('07-05-2019','DD-MM-YY'),30,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6500,'MALE',TO_DATE('10-01-2018','DD-MM-YY'),10,70);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,7000,'MALE',TO_DATE('20-01-2020','DD-MM-YY'),50,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,3000,'MALE',TO_DATE('15-02-2018','DD-MM-YY'),70,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,2500,'MALE',TO_DATE('01-01-2019','DD-MM-YY'),10,80);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,7500,'MALE',TO_DATE('06-04-2020','DD-MM-YY'),80,70);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,4500,'MALE',TO_DATE('02-10-2019','DD-MM-YY'),80,30);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,3500,'MALE',TO_DATE('01-07-2018','DD-MM-YY'),10,20);

SELECT * FROM EMPLOYEE;

---------------
DESCRIBE CUSTOMER;

INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'KURATOLI,DHAKA','01711353541','01786858765','34615252',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'KURIL,DHAKA','01764547807','01765656560','23450989',60);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'BASUNDHARA,DHAKA','01345673890','01356889605','85674435',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'GULSHAN,DHAKA','01689467804','01923454323','53467897',40);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'KHILKHET,DHAKA','01776546708','01564748897','64789763',50);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'BANANI,DHAKA','01478042329','01632529520','78656765',80);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'BANANI,DHAKA','01767652897','01785435689','97456489',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'UTTARA,DHAKA','01885352572','01978042320','12354278',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'DHANMONDI,DHAKA','01956435609','01965789467','72728384',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'MIRPUR-10,DHAKA','01534326890','01763567898','43563590',NULL);
SELECT * FROM CUSTOMER;
--------------

DESCRIBE GRADE;

INSERT INTO GRADE VALUES('FIRST GRADE',100,2000);
INSERT INTO GRADE VALUES('SECOND GRADE',2001,5500);
INSERT INTO GRADE VALUES('THIRD GRADE',5501,10000);

SELECT * FROM GRADE;
-----------------------
DESCRIBE PERSON;

INSERT INTO PERSON VALUES('NILL ROY','01785645678',TO_DATE('10-07-2000','DD-MM-YY'),10,20);
INSERT INTO PERSON VALUES('AVIJIT ROY','01797345678',TO_DATE('30-07-1998','DD-MM-YY'),20,NULL);
INSERT INTO PERSON VALUES('RATOL SAHA','01364789846',TO_DATE('12-01-1995','DD-MM-YY'),30,40);
INSERT INTO PERSON VALUES('ARAFAT HOSSEN','01654326789',TO_DATE('03-10-2000','DD-MM-YY'),40,NULL);
INSERT INTO PERSON VALUES('ARNOB ISLAM','01675456789',TO_DATE('25-06-1996','DD-MM-YY'),60,90);
INSERT INTO PERSON VALUES('SAZZAD HOSSAIN','01567356789',TO_DATE('15-11-1998','DD-MM-YY'),NULL,10);
INSERT INTO PERSON VALUES('ARIFUL ISLAM','01767567890',TO_DATE('17-04-1998','DD-MM-YY'),NULL,30);
INSERT INTO PERSON VALUES('SHOWMITRA ROY','01786456789',TO_DATE('30-12-2001','DD-MM-YY'),70,NULL);
INSERT INTO PERSON VALUES('HAFIZUL HAQUE','01867898976',TO_DATE('27-02-2000','DD-MM-YY'),80,NULL);
INSERT INTO PERSON VALUES('MD DINISLAM','01304636788',TO_DATE('01-02-1998','DD-MM-YY'),90,NULL);
INSERT INTO PERSON VALUES('NAZMUS SAKIB','01578756789',TO_DATE('11-08-1997','DD-MM-YY'),NULL,70);
INSERT INTO PERSON VALUES('NAHIDUL ISLAM','01745678356',TO_DATE('16-10-1999','DD-MM-YY'),NULL,80);
INSERT INTO PERSON VALUES('ANTOR ISLAM','01356765678',TO_DATE('23-11-2000','DD-MM-YY'),NULL,100);
INSERT INTO PERSON VALUES('INJAMUL ISLAM ','01646789879',TO_DATE('20-06-1999 ','DD-MM-YY'),100,NULL);
SELECT * FROM PERSON;


DESCRIBE PIZZA;

INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'PIZZA ALLA PALA',20,220,50);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'DETROIT-STYLE PIZZA',15,250,60);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'GARLIC FINGERS',12,175,65);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'LOUIS PIZZA',25,350,85);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'NIKIS PIZZA',15,350,70);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'EMMY SQUARED',05,235,80);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'BLOWERS GRAFTON',12,399,75);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'TOMS PIZZA',20,235,85);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'LITTLE RED BARN',18,349,90);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'MICHAELS PIZZERIA',06,450,75);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'WALDO PIZZA',10,299,95);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'PIZZA ORTOLANA',08,499,95);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'COLONY GRILL',15,599,65);
INSERT INTO PIZZA VALUES(PIZZA_SEQUENCE.NEXTVAL,'PIZZA RUSTICA',10,355,90);
SELECT * FROM PIZZA;

ALTER TABLE RECEIPT RENAME COLUMN ORDERNO TO RECEIPTNO; 
ALTER TABLE RECEIPT ADD(
    PIZZANO NUMBER(25) CONSTRAINT FK_RPIZZANO REFERENCES PIZZA,
    CUSNO NUMBER(25) CONSTRAINT FK_RCUSNO REFERENCES CUSTOMER
);

INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',10,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',20,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,30,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,50,30);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',40,20);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',NULL,NULL);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',20,40);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',10,60);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',30,60);
SELECT * FROM RECEIPT;
------------------------------
SELECT * FROM PERSON;
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;
SELECT * FROM HOMETOWN;
SELECT * FROM GRADE;
SELECT * FROM PIZZA;
SELECT * FROM RECEIPT;

----------------------------

-- SHOW ALL EMPLOYEES FROM PERSON TABLE
SELECT * FROM PERSON WHERE EMPNO IS NOT NULL;
-- SHOW ALL CUSTOMERS FROM PERSON TABLE
SELECT * FROM PERSON WHERE CUSNO IS NOT NULL;


-- SHOW THE LENGTH OF ALL PERSON
SELECT NAME, LENGTH(NAME) FROM PERSON;

-- RETRIVE THE MAXIMUM LENGTH OF PERSONS NAME
SELECT MAX(LENGTH(NAME)) FROM PERSON;

-- SHOW INFROMATION OF PIZZA FROM THE RECEIPT 40
SELECT * FROM PIZZA WHERE PIZZANO = (SELECT PIZZANO FROM RECEIPT WHERE RECEIPTNO = 40);
-- SHOW INFORMATION OF PIZZA EXCEPT THE PIZZA GIVEN IN RECEIPT 20
SELECT * FROM PIZZA WHERE PIZZANO <> (SELECT PIZZANO FROM RECEIPT WHERE RECEIPTNO = 20);

-- SHOW ALL THE SOLD PIZZA 
SELECT * FROM PIZZA WHERE PIZZANO IN (SELECT PIZZANO FROM RECEIPT);

-- SHOW ALL THE PERSONS INFROMATION FROM DATABASE WHO HAVE SAME NAME LENTH OF THE SOLD PIZZA NAMES.
SELECT * FROM PERSON WHERE LENGTH(NAME) IN (SELECT LENGTH(PIZZANAME) FROM PIZZA WHERE PIZZANO IN (SELECT PIZZANO FROM RECEIPT));

-- RETRIVE ALL INFORMATION OF THE EMPLOYEES WHO IS FROM JAMALPUR
SELECT * FROM PERSON WHERE EMPNO IN (SELECT EMPNO FROM EMPLOYEE WHERE HOMETOWNNO IN (SELECT HOMETOWNNO FROM HOMETOWN WHERE HOMETOWNNAME = 'JAMALPUR'));

-- SHOW ALL CUSTOMER INFO WHO HAS BOUGHT AT LEAST ONE PIZZA
SELECT P.* FROM PERSON P,RECEIPT R WHERE P.CUSNO = R.CUSNO;
SELECT * FROM RECEIPT;

-- FIND THE GRADE OF EVERY EMPLOYEE 
SELECT S.GRADENAME,E.EMPNO,E.SALARY FROM EMPLOYEE E,GRADE S WHERE E.SALARY BETWEEN S.LOWGRADE AND S.HIGHGRADE;

-- SHOW ALL PIZZA WITH THEIR RECEIPTNO AND PAID STATUS
SELECT RECEIPTNO,PIZZA.PIZZANAME,PIZZA.PRICE,STATUS FROM PIZZA LEFT OUTER JOIN RECEIPT ON(RECEIPT.PIZZANO = PIZZA.PIZZANO AND RECEIPT.STATUS = 'PAID');

INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',NULL,NULL);
-- SHOW ALL INFORMATION OF RECEIPT AND SELECTED INFORMATION OF PIZZA TABLE
SELECT RECEIPTNO,PIZZA.PIZZANAME,PIZZA.PRICE,STATUS FROM PIZZA RIGHT OUTER JOIN RECEIPT ON(RECEIPT.PIZZANO = PIZZA.PIZZANO);

-- SHOW ALL INFORMATION OF PERSON AND CUSTOMER USING FULL OUTER JOIN
SELECT PERSON.*,CUSTOMER.* FROM PERSON FULL OUTER JOIN CUSTOMER ON (PERSON.CUSNO = CUSTOMER.CUSNO);

--

INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',20,40);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',10,60);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',30,60);


--- FIND ALL THE CUSTOMER NUMBER WHO HAS BOUGHT SAME PIZZA
SELECT 'CUSTOMER '||R1.CUSNO||' AND CUSTOMER '|| R2.CUSNO||' HAS BOUGHT SAME PIZZA' "CUSTOMER0-PIZZA" FROM RECEIPT R1,RECEIPT R2 WHERE R1.RECEIPTNO <> R2.RECEIPTNO AND R1.PIZZANO = R2.PIZZANO;


--SHOW RECEIPT OF ALL CUSTOMER USING A VIEW NAMED PIZZAVIEW
CREATE OR REPLACE VIEW PIZZAVIEW (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, PIZZA_NAME,ORDER_STATUS) AS SELECT PERSON.NAME,PERSON.PHONE,RECEIPT.CUSNO,PIZZA.PIZZANAME,NVL(RECEIPT.STATUS,'STATUS LOADING') FROM PERSON,RECEIPT,PIZZA WHERE PERSON.CUSNO = RECEIPT.CUSNO AND PIZZA.PIZZANO = RECEIPT.PIZZANO;
SELECT * FROM PIZZAVIEW;