CREATE TABLE BRANCH
(
    BRANCHNO NUMBER(15) CONSTRAINT PK_BRANCHNO PRIMARY KEY,
    BRANCHNAME VARCHAR2(25),
    LOCATION VARCHAR2(25)
);
DESC BRANCH;

CREATE TABLE DISTRICT
(
    DISNO NUMBER(15) CONSTRAINT PK_DISNO PRIMARY KEY,
    DISNAME VARCHAR2(25)
);
DESC DISTRICT;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(15) CONSTRAINT PK_EMPNO PRIMARY KEY,
    SALARY NUMBER(7),
    GENDER VARCHAR2(10),
    JOINDATE DATE,
    DISNO NUMBER(15) CONSTRAINT FK_DISNO REFERENCES DISTRICT
);
DESC EMPLOYEE;

CREATE TABLE CUSTOMER
(
     CUSNO NUMBER(30) CONSTRAINT PK_CUSNO PRIMARY KEY,
     ADDRESS VARCHAR2(35),
     BKASH VARCHAR2(35),
     NAGAD VARCHAR2(35),
     CCARD VARCHAR2(35),
     EMPNO CONSTRAINT FK_CEMPNO REFERENCES EMPLOYEE
);
DESCRIBE CUSTOMER;

CREATE TABLE PERSON
(
    NAME VARCHAR2(30),
    CELL VARCHAR2(20),
    DOB DATE,
    EMPNO NUMBER(15) CONSTRAINT FK_EMPNO REFERENCES EMPLOYEE,
    CUSNO NUMBER(15) CONSTRAINT FK_CUSNO REFERENCES CUSTOMER
);
DESC PERSON;

CREATE TABLE  PASTRY
(
     PASTRYNO NUMBER(30) CONSTRAINT PK_PASTRYNO PRIMARY KEY,     
     PASTRYNAME VARCHAR2(30),
     STOCK NUMBER(20),
     PRICE NUMBER(30),
     PROFIT NUMBER(20) 
 );
DESC PASTRY;

CREATE TABLE RECEIPT
(
    ORDERNO NUMBER(20) CONSTRAINT PK_ODERNO PRIMARY KEY,
    STATUS VARCHAR(20) 
);
DESC RECEIPT;

CREATE TABLE SCALE 
(
    GRADE  VARCHAR2(20), 
    HIGH NUMBER(20),
    LOW NUMBER(20)
);
DESCRIBE SCALE;



----------------
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;
SELECT * FROM DISTRICT;
SELECT * FROM SCALE;
SELECT * FROM PERSON;
SELECT * FROM PASTRY;
SELECT * FROM RECEIPT;
--------------
DESC BRANCH;
DESC CUSTOMER;
DESC EMPLOYEE;
DESC DISTRICT;
DESC SCALE;
DESC PERSON;
DESC PASTRY;
DESC RECEIPT;
-------------


--------INSERTION-----------
CREATE SEQUENCE CUSTOMER_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE EMPLOYEE_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;

DROP SEQUENCE BRANCH_SEQUENCE;
CREATE SEQUENCE BRANCH_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE DISTRICT_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE SCALE_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE PERSON_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
DROP SEQUENCE PASTRY_SEQUENCE;
CREATE SEQUENCE PASTRY_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
CREATE SEQUENCE RECEIPT_SEQUENCE MINVALUE 10 MAXVALUE 9999 START WITH 10 NOCACHE NOCYCLE INCREMENT BY 10;
--------
-----MAKE EMPLOYEES FIRST

ALTER TABLE BRANCH DROP COLUMN LOCATION;

INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS DHANMONDI');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS DHAKA');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS RAJSHAI');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS SYLET');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS FARIDPUR');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS KHULNA');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS RUNGPUR');
INSERT INTO BRANCH VALUES(BRANCH_SEQUENCE.NEXTVAL,'PUTULY SWEETS DINAJPUR');
SELECT * FROM BRANCH;

TRUNCATE TABLE BRANCH;

-------
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'FARIDPUR');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'RAJSHAI');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'KHULNA');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'SYLET');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'RUNGPUR');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'DINAJPUR');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'KUSTIA');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'MAGORA');
INSERT INTO DISTRICT VALUES(DISTRICT_SEQUENCE.NEXTVAL,'JOSSOR');

SELECT * FROM DISTRICT;
------
SELECT * FROM BRANCH;
SELECT * FROM EMPLOYEE;
DESC EMPLOYEE;
ALTER TABLE EMPLOYEE DROP COLUMN BRANCHNO;

ALTER TABLE EMPLOYEE ADD(BRANCHNO NUMBER(15) CONSTRAINT FK_EBRANCH REFERENCES BRANCH);


----------------

INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6000,'MALE',TO_DATE('01-01-2017','DD-MM-YY'),10,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6000,'MALE',TO_DATE('01-01-2009','DD-MM-YY'),10,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,5000,'MALE',TO_DATE('04-01-2017','DD-MM-YY'),20,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,7000,'MALE',TO_DATE('07-01-2018','DD-MM-YY'),30,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,4000,'MALE',TO_DATE('01-01-2016','DD-MM-YY'),100,70);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6500,'MALE',TO_DATE('09-01-2017','DD-MM-YY'),50,50);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,2500,'MALE',TO_DATE('09-01-2019','DD-MM-YY'),70,20);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,2000,'MALE',TO_DATE('10-01-2015','DD-MM-YY'),10,80);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,8000,'MALE',TO_DATE('15-01-2019','DD-MM-YY'),80,70);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,6500,'MALE',TO_DATE('03-01-2016','DD-MM-YY'),80,30);
INSERT INTO EMPLOYEE VALUES(EMPLOYEE_SEQUENCE.NEXTVAL,3000,'MALE',TO_DATE('01-01-2015','DD-MM-YY'),100,20);

SELECT * FROM EMPLOYEE;

---------

DESC CUSTOMER;

INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'SAVAR DOHS,DHAKA','01878042329','01878042320','123124123',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'SAVAR DOHS,DHAKA','01778042329','01778042320','123124123',10);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'BARIDHARA,DHAKA','01578042329','01578042320','753124129',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'MIRPUR-1,DHAKA','01378042322','01878042320','623124125',30);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'BONANI,DHAKA','01678042329','01878042320','693124192',60);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'FARMGET,DHAKA','01478042329','01378042385','453124122',90);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'KHILGAON,DHAKA','01778042355','01868042342','443124122',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'AJIMPUR,DHAKA','01666042329','01978042320','243124125',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'UTTARA,DHAKA','01378042329','01378042370','863124128',NULL);
INSERT INTO CUSTOMER VALUES(CUSTOMER_SEQUENCE.NEXTVAL,'GULSHAN,DHAKA','01677042329','01978042321','813124126',NULL);
SELECT * FROM CUSTOMER;

----
DESC SCALE;

ALTER TABLE SCALE DROP COLUMN LOW;
ALTER TABLE SCALE ADD LOW NUMBER(20);

INSERT INTO SCALE VALUES('FIRST GRADE',500,1500);
INSERT INTO SCALE VALUES('SECOND GRADE',1501,5000);
INSERT INTO SCALE VALUES('THIRD GRADE',5001,10000);

SELECT * FROM SCALE;

------

DESC PERSON;
SELECT * FROM EMPLOYEE; -- 10 - 100
SELECT * FROM CUSTOMER; -- 10 - 100

INSERT INTO PERSON VALUES('TONMOY DEY','01878042329',TO_DATE('01-10-1997','DD-MM-YY'),10,20);
INSERT INTO PERSON VALUES('SHAKIL MOLLA','01378042329',TO_DATE('12-05-1990','DD-MM-YY'),20,NULL);
INSERT INTO PERSON VALUES('HAJJAJ BIN SONOSI','01878042329',TO_DATE('21-11-1957','DD-MM-YY'),30,40);
INSERT INTO PERSON VALUES('SHADIN','01578042329',TO_DATE('01-06-1994','DD-MM-YY'),40,NULL);
INSERT INTO PERSON VALUES('RAFSAN','01678042329',TO_DATE('01-08-1993','DD-MM-YY'),50,60);
INSERT INTO PERSON VALUES('AYMAN SADIK','01978042329',TO_DATE('26-02-1967','DD-MM-YY'),60,90);
INSERT INTO PERSON VALUES('SULAYMAN  SUKON','01368042329',TO_DATE('19-12-1960','DD-MM-YY'),NULL,10);
INSERT INTO PERSON VALUES('AREF','01698042329',TO_DATE('23-10-1998','DD-MM-YY'),NULL,30);
INSERT INTO PERSON VALUES('TOWFIQ-E-ELAHI','01778042329',TO_DATE('01-05-1988','DD-MM-YY'),70,NULL);
INSERT INTO PERSON VALUES('KAZI FOYSAL','01688042329',TO_DATE('02-08-1992','DD-MM-YY'),80,NULL);
INSERT INTO PERSON VALUES('FERDOUS AMIN LIAN','01888042329',TO_DATE('29-10-1985','DD-MM-YY'),NULL,50);
INSERT INTO PERSON VALUES('TASNIM HASAN','01968042329',TO_DATE('21-03-1991','DD-MM-YY'),90,NULL);
INSERT INTO PERSON VALUES('SABBIR ROHOMAN','01568042329',TO_DATE('01-11-1990','DD-MM-YY'),NULL,70);
INSERT INTO PERSON VALUES('WASIB AHAMED','01968042329',TO_DATE('01-07-2000','DD-MM-YY'),NULL,80);
INSERT INTO PERSON VALUES('SAIKUL ISLAM','01708042329',TO_DATE('01-07-2003','DD-MM-YY'),NULL,100);
INSERT INTO PERSON VALUES('ABDULA ','01898042329',TO_DATE('28-02-1986','DD-MM-YY'),100,NULL);
SELECT * FROM PERSON;

SELECT * FROM CUSTOMER WHERE EMPNO IS NOT NULL;

-------------
DESC PASTRY;
TRUNCATE TABLE PASTRY;

INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'DARK CHOCOLET',10,120,48);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'VENILA STRABERRY',13,165,55);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'CLASSIC CUFF PASTRY',05,300,70);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'WHITE CHOCOLET',20,80,20);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'BUTTER SCOTCH ',12,120,25);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'FLAKY PASTRY',07,110,30);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'DARK FOREST',16,135,35);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'CHORLEY CAKE',15,70,15);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'RED VELVED',09,225,80);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'BAHULU',07,70,20);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'BAKLAVA',06,50,15);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'ALOO PIE',04,160,35);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'BEAVER TAIL',06,130,30);
INSERT INTO PASTRY VALUES(PASTRY_SEQUENCE.NEXTVAL,'APPLE PIE',13,85,25);

SELECT * FROM PASTRY;

--------------------

DESC RECEIPT;
SELECT * FROM PASTRY;
SELECT * FROM CUSTOMER;

ALTER TABLE RECEIPT RENAME COLUMN ORDERNO TO RECEIPTNO; 
ALTER TABLE RECEIPT ADD(
    PASTRYNO NUMBER(20) CONSTRAINT FK_RPASTRYNO REFERENCES PASTRY,
    CUSNO NUMBER(20) CONSTRAINT FK_RCUSNO REFERENCES CUSTOMER
);

INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',10,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',20,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,30,10);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,50,30);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',40,20);

INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',80,30);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',70,40);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,50,50);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,50,60);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',60,70);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',20,80);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'PAID',30,90);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,NULL,90,100);
-- INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,PAID,50,30);
INSERT INTO RECEIPT VALUES(RECEIPT_SEQUENCE.NEXTVAL,'RETURED',10,100);

SELECT * FROM RECEIPT;

------

SELECT * FROM PERSON;
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;
SELECT * FROM DISTRICT;
SELECT * FROM SCALE;
SELECT * FROM PASTRY;
SELECT * FROM RECEIPT;



--SHOW RECEIPT USING A VIEW
CREATE OR REPLACE VIEW PASTRYVIEW (CUSTOMER_NAME, PHONE, CUSTOMER_NUMBER, PASTRY_NAME,ORDER_STATUS) AS SELECT PERSON.NAME,PERSON.CELL,RECEIPT.CUSNO,PASTRY.PASTRYNAME,NVL2(RECEIPT.STATUS,RECEIPT.STATUS,'STATUS PENDING') FROM PERSON,RECEIPT,PASTRY WHERE PERSON.CUSNO = RECEIPT.CUSNO AND PASTRY.PASTRYNO = RECEIPT.PASTRYNO;
SELECT * FROM PASTRYVIEW;

---SHOW ALL THE WRONG INFORMATION WHERE TWO EMPLOYEE HAS SAME PHONE NUMBER
SELECT P1.NAME,P1.CELL, P2.CELL,P2.NAME FROM PERSON P1,PERSON P2 WHERE P1.CELL = P2.CELL AND P1.EMPNO <> P2.EMPNO;

--- RETRIVE ALL DATAS FROM FOLLOWING TABLES USING ONE QUERY : PERSON & EMPLOYEE
SELECT PERSON.*,EMPLOYEE.* FROM PERSON FULL OUTER JOIN EMPLOYEE ON (EMPLOYEE.EMPNO = PERSON.EMPNO); 

---SHOW THE DISTRICT INFORMATION OF ALL EMPLOYEES AND ALL THE DISTRICT INFORMATIONS
SELECT DISTRICT.*,EMPLOYEE.* FROM EMPLOYEE RIGHT OUTER JOIN DISTRICT ON (EMPLOYEE.DISNO = DISTRICT.DISNO) ORDER BY DISTRICT.DISNO DESC;
---------- SHOW ALL BRANCH INFORMATION AND EMPLOYEE NUMBER FROM BRANCH TABLE
SELECT BRANCH.*,EMPLOYEE.EMPNO FROM BRANCH LEFT OUTER JOIN EMPLOYEE ON (BRANCH.BRANCHNO = EMPLOYEE.BRANCHNO);

DESC EMPLOYEE;
-- NON-EQUIJOIN : FIND THE PAYSCALE OF EVERY EMPLOYEE 
SELECT E.EMPNO,E.SALARY,S.GRADE FROM EMPLOYEE E,SCALE S WHERE E.SALARY BETWEEN S.HIGH AND S.LOW;

-- EQUIJOIN : SHOW ALL EMPLOYEE WHO IS EARNING MORE THAN 4000 
SELECT P.* FROM PERSON P,EMPLOYEE E WHERE P.EMPNO = E.EMPNO AND E.SALARY > 4000;  

---FIND ALL CUSTOMER INFORMATION WHO IS FROM DHAKA AND PURCHASED ATLEAST ONE PASTRY 
SELECT * FROM PERSON WHERE CUSNO IN (SELECT CUSNO FROM CUSTOMER WHERE CUSNO IN (SELECT CUSNO FROM RECEIPT) AND ADDRESS LIKE '%DHAKA');

---- RETRIVE ALL EMPLOYEE INFORMATION FROM PERSON TABLE WHERE BRANCH FROM DHAKA
SELECT * FROM PERSON WHERE EMPNO IN (SELECT EMPNO FROM EMPLOYEE WHERE BRANCHNO IN (SELECT BRANCHNO FROM BRANCH WHERE BRANCHNAME LIKE '%DHAKA'));

-- SHOW ALL INFORMATION OF A EMPLOYEE WHO HAS SALARY GREATER THAN 5000
SELECT * FROM PERSON WHERE EMPNO IN (SELECT EMPNO FROM EMPLOYEE WHERE SALARY > 5000);

UPDATE DISTRICT SET DISNAME = 'DHAKA' WHERE DISNO = 10;

-- FIND ALL EMPLOYEES WHO'S HOMETOWN IS IN FARIDPUR
SELECT * FROM EMPLOYEE WHERE DISNO = (SELECT DISNO FROM DISTRICT WHERE DISNAME = 'FARIDPUR'); 
-- FIND THE CUSTOMER INFORMATION FROM PERSONAL TABLE WHERE EMPLOYEE IS 10
SELECT * FROM PERSON WHERE CUSNO = (SELECT CUSNO FROM CUSTOMER WHERE EMPNO = 10);

-- FIND ALL PERSON WHO'S NAME HAS FIRST WORD 'T'
SELECT * FROM PERSON WHERE NAME LIKE 'T%';
-- SHOW ALL PASTRY PRICES GREATER THAN 200
SELECT * FROM PASTRY WHERE PRICE > 200;

-- FIND THE REMAINDER WHEN PASTRY PRICE IS DEVIDED BY 2
SELECT PASTRYNAME,PRICE,MOD(PRICE,2) FROM PASTRY;
-- FIND THE MOST EXPENSIVE PASTRY FROM THE PASTRY SHOP
SELECT MAX(PRICE) FROM PASTRY;







